<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;



/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    // compteur 
    public function countAll() {
        $query = $this->createQueryBuilder("m")
                ->select("count(m)")
                ->getQuery();
        
        $count = $query->getSingleScalarResult();
        return $count;
    }
    
    // année mini film bdd
    public function minYear() {
       $query = $this->createQueryBuilder('m')
                ->select("MIN(m.year)")
                ->getQuery();
        
        // singlescalar pour obtenir directement le nombre(sans array autour)
        $minY = $query->getSingleScalarResult();
        return $minY; 
    }
    
    // année maxi film bdd
    public function maxYear() {
       $query = $this->createQueryBuilder('m')
                ->select("MAX(m.year)")
                ->getQuery();
        
        // singlescalar pour obtenir directement le nombre(sans array autour)
        $maxY = $query->getSingleScalarResult();
        return $maxY; 
    }
    
    public function filtre($minYear, $maxYear,$offset) {
        $qb = $this->createQueryBuilder("m")
                ->select("m")
                ->andWhere('m.year BETWEEN :min AND  :max')
                ->setParameter('min',$minYear)
                ->setParameter('max',$maxYear)
                ->setMaxResults(50)
                ->setFirstResult($offset);
        $result = $qb->getQuery()
                ->getResult();

        return $result;
    }
     
}
